create table users (
    id bigint generated by default as identity primary key,
    handle varchar(80) not null unique,
    display_name varchar(120) not null
);

create table projects (
    id bigint generated by default as identity primary key,
    owner_user_id bigint not null references users (id),
    slug varchar(120) not null unique,
    title varchar(160) not null,
    summary varchar(400) not null,
    status varchar(20) not null,
    created_at timestamp not null,
    constraint project_status_check check (status in ('active', 'completed', 'dormant'))
);

create table project_roles (
    id bigint generated by default as identity primary key,
    project_id bigint not null references projects (id) on delete cascade,
    title varchar(120) not null,
    commitment varchar(80) not null,
    is_founder boolean not null default false,
    is_open boolean not null default true,
    sort_order integer not null default 0
);
