alter table users add column email varchar(320);
alter table users add column created_at timestamp not null default current_timestamp;

update users
set email = case id
    when 1 then 'avery@example.test'
    when 2 then 'nora@example.test'
    when 3 then 'elliot@example.test'
    when 4 then 'mika@example.test'
    else concat('user-', id, '@example.test')
end;

alter table users alter column email set not null;
alter table users add constraint users_email_unique unique (email);

create table password_credentials (
    user_id bigint primary key references users (id) on delete cascade,
    password_hash varchar(120) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table invite_links (
    id bigint generated by default as identity primary key,
    created_by_user_id bigint unique references users (id) on delete set null,
    token varchar(120) not null unique,
    allowed_email varchar(320),
    is_active boolean not null default true,
    use_count integer not null default 0,
    created_at timestamp not null default current_timestamp
);

create table invite_redemptions (
    id bigint generated by default as identity primary key,
    invite_link_id bigint not null references invite_links (id) on delete cascade,
    used_by_user_id bigint not null references users (id) on delete cascade,
    used_email varchar(320) not null,
    redeemed_at timestamp not null default current_timestamp
);

create table sessions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    token_hash varchar(64) not null unique,
    created_at timestamp not null default current_timestamp,
    expires_at timestamp not null,
    last_seen_at timestamp not null default current_timestamp
);

create index invite_redemptions_invite_link_idx on invite_redemptions (invite_link_id);
create index sessions_user_id_idx on sessions (user_id);
