create table if not exists project_links (
    id bigint generated by default as identity primary key,
    project_id bigint not null references projects (id) on delete cascade,
    label varchar(40) not null,
    url varchar(2048) not null,
    sort_order integer not null default 0,
    constraint project_link_label_length_check check (length(label) between 2 and 40),
    constraint project_link_url_length_check check (length(url) between 8 and 2048),
    constraint project_link_sort_order_check check (sort_order >= 0)
);

create index if not exists project_links_project_id_sort_idx
    on project_links (project_id, sort_order, id);

create table if not exists project_images (
    id bigint generated by default as identity primary key,
    project_id bigint not null references projects (id) on delete cascade,
    content_type varchar(32) not null,
    size_bytes integer not null,
    image_data bytea not null,
    alt_text varchar(160) not null default '',
    sort_order integer not null default 0,
    created_at timestamp not null default current_timestamp,
    constraint project_image_content_type_check check (content_type in ('image/jpeg', 'image/png', 'image/webp')),
    constraint project_image_size_check check (size_bytes > 0 and size_bytes <= 2097152),
    constraint project_image_alt_text_length_check check (length(alt_text) <= 160),
    constraint project_image_sort_order_check check (sort_order >= 0)
);

create index if not exists project_images_project_id_sort_idx
    on project_images (project_id, sort_order, id);
