create table if not exists job_applications (
    id bigint generated by default as identity primary key,
    role_id bigint not null references project_roles (id) on delete cascade,
    applicant_user_id bigint not null references users (id) on delete cascade,
    fit varchar(2000) not null,
    availability varchar(500) not null default '',
    created_at timestamp not null default current_timestamp,
    constraint job_application_fit_length_check check (length(fit) between 20 and 2000),
    constraint job_application_availability_length_check check (length(availability) <= 500),
    constraint job_application_role_applicant_unique unique (role_id, applicant_user_id)
);

create index if not exists job_applications_applicant_created_idx
    on job_applications (applicant_user_id, created_at desc);
