create table if not exists users (
    id bigint generated by default as identity primary key,
    handle varchar(80) not null unique,
    display_name varchar(120) not null
);

create table if not exists projects (
    id bigint generated by default as identity primary key,
    owner_user_id bigint not null references users (id),
    slug varchar(120) not null unique,
    title varchar(120) not null,
    description varchar(1024) not null,
    status varchar(20) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint project_title_length_check check (length(title) between 5 and 120),
    constraint project_description_length_check check (length(description) between 40 and 1024),
    constraint project_status_check check (status in ('active', 'completed', 'dormant'))
);

create table if not exists project_roles (
    id bigint generated by default as identity primary key,
    project_id bigint not null references projects (id) on delete cascade,
    title varchar(80) not null,
    commitment varchar(280) not null,
    is_founder boolean not null default false,
    is_open boolean not null default true,
    sort_order integer not null default 0,
    constraint project_role_title_length_check check (length(title) between 3 and 80),
    constraint project_role_commitment_length_check check (
        (is_founder = true and length(commitment) between 10 and 280)
        or
        (is_founder = false and length(commitment) between 3 and 80)
    ),
    constraint project_role_founder_open_check check (is_founder = false or is_open = false),
    constraint project_role_sort_order_check check (sort_order >= 0)
);

alter table users alter column id restart with 1000;
alter table projects alter column id restart with 1000;
alter table project_roles alter column id restart with 1000;
