alter table users add column if not exists email varchar(320);
alter table users add column if not exists created_at timestamp not null default current_timestamp;

update users
set email = case id
    when 1 then 'avery@example.test'
    when 2 then 'nora@example.test'
    when 3 then 'elliot@example.test'
    when 4 then 'mika@example.test'
    else concat('user-', id, '@example.test')
end
where email is null;

alter table users alter column email set not null;
create unique index if not exists users_email_unique on users (email);

create table if not exists password_credentials (
    user_id bigint primary key references users (id) on delete cascade,
    password_hash varchar(120) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists invite_links (
    id bigint generated by default as identity primary key,
    token_hash varchar(64) not null unique,
    is_active boolean not null default true,
    use_count integer not null default 0,
    created_at timestamp not null default current_timestamp
);

create table if not exists invite_redemptions (
    id bigint generated by default as identity primary key,
    invite_link_id bigint not null references invite_links (id) on delete cascade,
    used_by_user_id bigint not null references users (id) on delete cascade,
    used_email varchar(320) not null,
    redeemed_at timestamp not null default current_timestamp
);

create table if not exists sessions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    token_hash varchar(64) not null unique,
    created_at timestamp not null default current_timestamp,
    expires_at timestamp not null,
    last_seen_at timestamp not null default current_timestamp
);

create index if not exists invite_redemptions_invite_link_idx on invite_redemptions (invite_link_id);
create index if not exists sessions_user_id_idx on sessions (user_id);
