alter table users add column if not exists email_verified_at timestamp;

update users
set email_verified_at = current_timestamp
where email_verified_at is null;

create table if not exists email_verification_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    token_hash varchar(64) not null unique,
    created_at timestamp not null default current_timestamp,
    expires_at timestamp not null
);

create index if not exists email_verification_tokens_user_id_idx
    on email_verification_tokens (user_id);

create table if not exists email_verification_sends (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    token_hash varchar(64) not null unique,
    created_at timestamp not null default current_timestamp
);

create index if not exists email_verification_sends_user_id_created_at_idx
    on email_verification_sends (user_id, created_at);

alter table projects drop constraint if exists projects_owner_user_id_fkey;
alter table projects drop constraint if exists constraint_c4;

alter table projects
    add constraint projects_owner_user_id_fkey
    foreign key (owner_user_id)
    references users (id)
    on delete cascade;
