create table if not exists project_comments (
    id bigint generated by default as identity primary key,
    project_id bigint not null references projects (id) on delete cascade,
    user_id bigint not null references users (id) on delete cascade,
    body varchar(1000) not null,
    created_at timestamp not null default current_timestamp,
    constraint project_comment_body_length_check check (length(body) between 1 and 1000)
);

create index if not exists project_comments_project_id_created_at_idx
    on project_comments (project_id, created_at);

create index if not exists project_comments_user_id_idx
    on project_comments (user_id);

create table if not exists project_comment_reads (
    project_id bigint not null references projects (id) on delete cascade,
    user_id bigint not null references users (id) on delete cascade,
    last_read_at timestamp not null,
    primary key (project_id, user_id)
);
