create table if not exists password_reset_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    token_hash varchar(64) not null unique,
    created_at timestamp not null default current_timestamp,
    expires_at timestamp not null
);

create index if not exists password_reset_tokens_user_id_idx
    on password_reset_tokens (user_id);
