app_service_http_port=8080
jdbc_database_url=jdbc:postgresql://localhost:5432/mitbauen
jdbc_database_user=mitbauen
jdbc_database_password=mitbauen_dev_password
app_run_migrations=false
app_migration_locations=filesystem:../db/migrations
